name: EconomyPlugin
version: '1.4'
main: ru.economyPlugin.EconomyPlugin
api-version: '1.20'
depend: [Vault]

commands:
  bal:
    aliases: [balance]
  pay: {}
  eco:
    aliases: [economy, economyplugin]

permissions:
  economy.eco: {}
  economy.bal.others: {}